--drop table

DROP TABLE INTERMEDIA_TURNO CASCADE CONSTRAINTS;
DROP TABLE ESTADO_MAQUIv2 CASCADE CONSTRAINTS;
DROP TABLE OPERARIO CASCADE CONSTRAINTS;
DROP TABLE TECNICOS_MANT CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE MAQUINA CASCADE CONSTRAINTS;
DROP TABLE PLANTA CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE AFP CASCADE CONSTRAINTS;
DROP TABLE SALUD CASCADE CONSTRAINTS;
DROP TABLE ESTADO_ACTIVO CASCADE CONSTRAINTS;
DROP TABLE ESTADO_MAQUI CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;
DROP TABLE CERTIFICACION CASCADE CONSTRAINTS;
DROP TABLE ESPECIALIDAD CASCADE CONSTRAINTS;
DROP TABLE TURNO CASCADE CONSTRAINTS;
DROP TABLE TIPO_TURNO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_REGION;

--creacion de tablas 
CREATE TABLE REGION (
    cod_region NUMBER NOT NULL,
    nombre     VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_REGION PRIMARY KEY (cod_region),
    CONSTRAINT REGION_nombre_UN UNIQUE (nombre)
);

CREATE SEQUENCE SEQ_REGION
    START WITH 21
    INCREMENT BY 1;

CREATE TABLE COMUNA (
    cod_comuna        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1050 INCREMENT BY 5),
    nombre            VARCHAR2(100) NOT NULL,
    REGION_cod_region NUMBER,
    CONSTRAINT PK_COMUNA PRIMARY KEY (cod_comuna),
    CONSTRAINT COMUNA_nombre_UN UNIQUE (nombre),
    CONSTRAINT FK_COMUNA_REGION FOREIGN KEY (REGION_cod_region)
        REFERENCES REGION (cod_region)
);


CREATE TABLE PLANTA (
    cod_planta        NUMBER NOT NULL,
    nombre            VARCHAR2(100) NOT NULL,
    direccion         VARCHAR2(200) NOT NULL,
    COMUNA_cod_comuna NUMBER,
    CONSTRAINT PK_PLANTA PRIMARY KEY (cod_planta),
    CONSTRAINT PLANTA_nombre_UN UNIQUE (nombre),
    CONSTRAINT FK_PLANTA_COMUNA FOREIGN KEY (COMUNA_cod_comuna)
        REFERENCES COMUNA (cod_comuna)
);

CREATE TABLE AFP (
    id_afp NUMBER NOT NULL,
    nombre VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_AFP PRIMARY KEY (id_afp),
    CONSTRAINT AFP_nombre_UN UNIQUE (nombre)
);

CREATE TABLE SALUD (
    id_salud NUMBER NOT NULL,
    nombre   VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_SALUD PRIMARY KEY (id_salud),
    CONSTRAINT SALUD_nombre_UN UNIQUE (nombre)
);

CREATE TABLE ESTADO_ACTIVO (
    id_estado   NUMBER NOT NULL,
    tipo_estado CHAR(2) NOT NULL,
    CONSTRAINT PK_ESTADO_ACTIVO PRIMARY KEY (id_estado),
    CONSTRAINT ESTADO_ACTIVO_tipo_estado_UN UNIQUE (tipo_estado)
);

CREATE TABLE ESTADO_MAQUI (
    id_estado   NUMBER NOT NULL,
    tipo_estado CHAR(1) NOT NULL,
    CONSTRAINT PK_ESTADO_MAQUI PRIMARY KEY (id_estado),
    CONSTRAINT ESTADO_MAQUI_tipo_estado_UN UNIQUE (tipo_estado)
);

CREATE TABLE CATEGORIA (
    id_categoria NUMBER NOT NULL,
    nombre       VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (id_categoria),
    CONSTRAINT CATEGORIA_nombre_UN UNIQUE (nombre)
);

CREATE TABLE CERTIFICACION (
    id_certificacion NUMBER NOT NULL,
    presencia        VARCHAR2(2) NOT NULL,
    CONSTRAINT PK_CERTIFICACION PRIMARY KEY (id_certificacion)
);

CREATE TABLE ESPECIALIDAD (
    id_especialidad NUMBER NOT NULL,
    nombre_e        VARCHAR2(20) NOT NULL,
    CONSTRAINT PK_ESPECIALIDAD PRIMARY KEY (id_especialidad),
    CONSTRAINT ESPECIALIDAD_nombre_e_UN UNIQUE (nombre_e)
);


CREATE TABLE MAQUINA (
    id_maquina   NUMBER NOT NULL,
    numero       NUMBER NOT NULL,
    tipo_maquina VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_MAQUINA PRIMARY KEY (id_maquina),
    CONSTRAINT CK_MAQUINA_NUM CHECK (numero > 0)
);

CREATE TABLE ESTADO_MAQUIv2 (
    ESTADO_MAQUI_id_estado NUMBER NOT NULL,
    MAQUINA_id_maquina     NUMBER NOT NULL,
    CONSTRAINT PK_ESTADO_MAQUIv2 PRIMARY KEY (ESTADO_MAQUI_id_estado, MAQUINA_id_maquina),
    CONSTRAINT FK_ESTADO_MAQUIv2_ESTADO FOREIGN KEY (ESTADO_MAQUI_id_estado)
        REFERENCES ESTADO_MAQUI (id_estado),
    CONSTRAINT FK_ESTADO_MAQUIv2_MAQUINA FOREIGN KEY (MAQUINA_id_maquina)
        REFERENCES MAQUINA (id_maquina)
);

CREATE TABLE TURNO (
    id_turno    NUMBER NOT NULL,
    hora_inicio CHAR(5) NOT NULL,
    hora_fin    CHAR(5) NOT NULL,
    fecha       DATE NOT NULL,
    CONSTRAINT PK_TURNO PRIMARY KEY (id_turno)
);

CREATE TABLE TIPO_TURNO (
    id_tipo NUMBER NOT NULL,
    tipo    VARCHAR2(10) NOT NULL,
    CONSTRAINT PK_TIPO_TURNO PRIMARY KEY (id_tipo),
    CONSTRAINT TIPO_TURNO_tipo_UN UNIQUE (tipo)
);

CREATE TABLE INTERMEDIA_TURNO (
    TURNO_id_turno     NUMBER NOT NULL,
    TIPO_TURNO_id_tipo NUMBER NOT NULL,
    CONSTRAINT PK_INTERMEDIA_TURNO PRIMARY KEY (TURNO_id_turno, TIPO_TURNO_id_tipo),
    CONSTRAINT FK_INTERMEDIA_TURNO_TURNO FOREIGN KEY (TURNO_id_turno)
        REFERENCES TURNO (id_turno),
    CONSTRAINT FK_INTERMEDIA_TURNO_TIPO FOREIGN KEY (TIPO_TURNO_id_tipo)
        REFERENCES TIPO_TURNO (id_tipo)
);

--empleado y subtipos

CREATE TABLE EMPLEADO (
    cod_empleado            NUMBER NOT NULL,
    rut                     NVARCHAR2(10) NOT NULL,
    nombres                 VARCHAR2(50) NOT NULL,
    a_paterno               VARCHAR2(50) NOT NULL,
    a_materno               VARCHAR2(50) NOT NULL,
    f_contrata              DATE NOT NULL,
    sueldo_base             NUMBER NOT NULL,
    area_respon             VARCHAR2(30),
    maximo_operarios        NUMBER,
    PLANTA_cod_planta       NUMBER NOT NULL,
    AFP_id_afp              NUMBER,
    SALUD_id_salud          NUMBER,
    MAQUINA_id_maquina      NUMBER,
    TURNO_id_turno          NUMBER NOT NULL,
    EMPLEADO_jefe           NUMBER,
    ESTADO_ACTIVO_id_estado NUMBER NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (cod_empleado, PLANTA_cod_planta, TURNO_id_turno, ESTADO_ACTIVO_id_estado),
    CONSTRAINT EMPLEADO_rut_UN UNIQUE (rut),
    CONSTRAINT CK_EMPLEADO_SUELDO CHECK (sueldo_base > 0),
    CONSTRAINT FK_EMPLEADO_AFP FOREIGN KEY (AFP_id_afp) REFERENCES AFP (id_afp),
    CONSTRAINT FK_EMPLEADO_SALUD FOREIGN KEY (SALUD_id_salud) REFERENCES SALUD (id_salud),
    CONSTRAINT FK_EMPLEADO_PLANTA FOREIGN KEY (PLANTA_cod_planta) REFERENCES PLANTA (cod_planta),
    CONSTRAINT FK_EMPLEADO_TURNO FOREIGN KEY (TURNO_id_turno) REFERENCES TURNO (id_turno),
    CONSTRAINT FK_EMPLEADO_MAQUINA FOREIGN KEY (MAQUINA_id_maquina) REFERENCES MAQUINA (id_maquina),
    CONSTRAINT FK_EMPLEADO_ESTADO FOREIGN KEY (ESTADO_ACTIVO_id_estado) REFERENCES ESTADO_ACTIVO (id_estado),
    CONSTRAINT FK_EMPLEADO_JEFE FOREIGN KEY (EMPLEADO_jefe, PLANTA_cod_planta, TURNO_id_turno, ESTADO_ACTIVO_id_estado)
        REFERENCES EMPLEADO (cod_empleado, PLANTA_cod_planta, TURNO_id_turno, ESTADO_ACTIVO_id_estado)
);

CREATE TABLE OPERARIO (
    cod_empleado                   NUMBER NOT NULL,
    cod_planta                     NUMBER NOT NULL,
    id_turno                       NUMBER NOT NULL,
    id_estado                      NUMBER NOT NULL,
    horas_turno                    NUMBER NOT NULL,
    CATEGORIA_id_categoria         NUMBER NOT NULL,
    CERTIFICACION_id_certificacion NUMBER NOT NULL,
    CONSTRAINT PK_OPERARIO PRIMARY KEY (cod_empleado, cod_planta, id_turno, id_estado),
    CONSTRAINT CK_OPERARIO_HORAS CHECK (horas_turno > 0),
    CONSTRAINT FK_OPERARIO_EMPLEADO FOREIGN KEY (cod_empleado, cod_planta, id_turno, id_estado)
        REFERENCES EMPLEADO (cod_empleado, PLANTA_cod_planta, TURNO_id_turno, ESTADO_ACTIVO_id_estado),
    CONSTRAINT FK_OPERARIO_CATEGORIA FOREIGN KEY (CATEGORIA_id_categoria) REFERENCES CATEGORIA (id_categoria),
    CONSTRAINT FK_OPERARIO_CERTIFICACION FOREIGN KEY (CERTIFICACION_id_certificacion) REFERENCES CERTIFICACION (id_certificacion)
);

CREATE TABLE TECNICOS_MANT (
    cod_empleado                 NUMBER NOT NULL,
    cod_planta                   NUMBER NOT NULL,
    id_turno                     NUMBER NOT NULL,
    id_estado                    NUMBER NOT NULL,
    certificacion                VARCHAR2(50) NOT NULL,
    tiempo_respuesta             CHAR(5) NOT NULL,
    ESPECIALIDAD_id_especialidad NUMBER NOT NULL,
    CONSTRAINT PK_TECNICOS_MANT PRIMARY KEY (cod_empleado, cod_planta, id_turno, id_estado),
    CONSTRAINT FK_TECNICOS_MANT_EMPLEADO FOREIGN KEY (cod_empleado, cod_planta, id_turno, id_estado)
        REFERENCES EMPLEADO (cod_empleado, PLANTA_cod_planta, TURNO_id_turno, ESTADO_ACTIVO_id_estado),
    CONSTRAINT FK_TECNICOS_MANT_ESPECIALIDAD FOREIGN KEY (ESPECIALIDAD_id_especialidad)
        REFERENCES ESPECIALIDAD (id_especialidad)
);

--faltaba añadir nombre a la tabla MAQUINA
ALTER TABLE MAQUINA
ADD nombre VARCHAR2(50) NOT NULL;

ALTER TABLE MAQUINA
ADD CONSTRAINT MAQUINA_NOMBRE_UN UNIQUE (nombre);

--Imgresar datos a tabla region 

insert into region (cod_region,nombre) 
values (SEQ_REGION.NEXTVAL, 'Región de Valparaiso'); 

insert into region (cod_region,nombre) 
values (SEQ_REGION.NEXTVAL, 'Región Metropolitana'); 

--ingresar datos a la tabla comuna 
INSERT INTO COMUNA (nombre, REGION_cod_region) 
VALUES ('Quilpué', 21);

INSERT INTO COMUNA (nombre, REGION_cod_region) 
VALUES ('Maipú', 22);

SELECT * FROM COMUNA;

select * from region;

--insertar datos en tabla planta
INSERT INTO PLANTA (cod_planta, nombre, direccion, COMUNA_cod_comuna)
VALUES (45, 'Planta Oriente', 'Camino Industrial 1234', 1050);

INSERT INTO PLANTA (cod_planta, nombre, direccion, COMUNA_cod_comuna)
VALUES (46, 'Planta Costa', 'Av. Vidrieras 890', 1055);

--insertar datos en la tabla turno
INSERT INTO TURNO (id_turno, hora_inicio, hora_fin, fecha)
VALUES (1, '07:00', '15:00', TO_DATE('2025-10-11', 'YYYY-MM-DD'));

INSERT INTO TURNO (id_turno, hora_inicio, hora_fin, fecha)
VALUES (2, '23:00', '07:00', TO_DATE('2025-10-11', 'YYYY-MM-DD'));

INSERT INTO TURNO (id_turno, hora_inicio, hora_fin, fecha)
VALUES (3, '15:00', '23:00', TO_DATE('2025-10-11', 'YYYY-MM-DD'));

--insert into en tipo turno
INSERT INTO TIPO_TURNO (id_tipo, tipo)
VALUES (1, 'Mañana');

INSERT INTO TIPO_TURNO (id_tipo, tipo)
VALUES (2, 'Noche');

INSERT INTO TIPO_TURNO (id_tipo, tipo)
VALUES (3, 'Tarde');

--en intermedia_turno 
INSERT INTO INTERMEDIA_TURNO (TURNO_id_turno, TIPO_TURNO_id_tipo)
VALUES (1, 1);

INSERT INTO INTERMEDIA_TURNO (TURNO_id_turno, TIPO_TURNO_id_tipo)
VALUES (2, 2);

INSERT INTO INTERMEDIA_TURNO (TURNO_id_turno, TIPO_TURNO_id_tipo)
VALUES (3, 3);

--hasta aca
--informe 1 con select
SELECT 
    tt.tipo AS TURNO,
    t.hora_inicio AS ENTRADA,
    t.hora_fin AS SALIDA
FROM 
    TURNO t
    JOIN INTERMEDIA_TURNO it ON t.id_turno = it.TURNO_id_turno
    JOIN TIPO_TURNO tt ON it.TIPO_TURNO_id_tipo = tt.id_tipo
WHERE 
    TO_NUMBER(SUBSTR(t.hora_inicio, 1, 2)) > 20
ORDER BY 
    t.hora_inicio DESC;


--informe 2 con el uso de select
SELECT 
    tt.tipo AS TURNO,
    t.hora_inicio AS ENTRADA,
    t.hora_fin AS SALIDA
FROM 
    TURNO t
    JOIN INTERMEDIA_TURNO it ON t.id_turno = it.TURNO_id_turno
    JOIN TIPO_TURNO tt ON it.TIPO_TURNO_id_tipo = tt.id_tipo
WHERE 
    TO_NUMBER(SUBSTR(t.hora_inicio, 1, 2)) BETWEEN 6 AND 14
ORDER BY 
    t.hora_inicio ASC;

